### ISSUE TITLE
Y-axis has xied width, overflow hidden

### ISSUE THREAD

**Issue by Orvacko** [juijs/jui-chart#52]
Hi, i have question about Y axis, why there is fixed max width ? For example herre, http://jui.io/play/chart/#grid_block_format.js,but is in all charts.

When you adujst Y axis data with, ex number formating, overflow is cut. 

![screen shot 2016-03-04 at 08 48 15](https://cloud.githubusercontent.com/assets/1727586/13521064/1224dbc0-e1e6-11e5-9777-cec9c342ffb2.png)

**Comment by easylogic** [comment]
hi @Orvacko.

jui chart  don't has   fixed max width for Y axis. 
Instead of, jui chart is use to a padding. 

see to below image.

![image](https://cloud.githubusercontent.com/assets/591983/13521733/1b50e0d4-e22e-11e5-937c-8e1b117b7c4e.png)

refer to padding samle   : http://jui.io/play/chart/#chart_padding.js 

```javascript
var chart = jui.include("chart.builder");

chart("#chart-content", {
    padding : {
        top : 100,  // default value is 50 
        left : 100   // default value is 50 
        right : 50,  // default value is 50 
        bottom : 50 // default value is 50 
    },

    or 

    padding : 100   // is equals to  { left : 100, right : 100,top : 100, bottom : 100  } 
   .... 
}
```

**Comment by Orvacko** [comment]
Thank you very much for help. After seeing your image, it is clear :)
